version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/Halifax
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:15"
      timezone: America/Halifax
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
